import { createApp } from 'vue'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import './styles/dialog-scrim.css'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faPlus,
  faTrash,
  faGear,
  faPaperPlane,
  faStop,
  faComments,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faArrowDown,
  faXmark,
  faWindowMaximize,
  faChevronDown,
  faChevronRight,
  faCheck,
  faClipboardList,
  faWrench,
  faArrowUpRightFromSquare,
  faListUl,
  faListCheck,
  faCircle,
  faCircleCheck,
  faArrowUp,
  faShieldHalved,
  faAnglesUp,
  faAnglesDown,
  faScaleBalanced,
  faUnlock,
  faSliders,
  faMicrochip,
  faCircleQuestion,
  faCircleNotch,
  faCircleExclamation,
  faKey,
  faRightFromBracket,
  faPenToSquare,
  faMagnifyingGlass,
  faFileExport,
  faEllipsis,
  faEllipsisVertical,
  faBars,
  faRobot,
  faTerminal,
  faFolder,
  faFolderOpen,
  faFile,
  faPuzzlePiece,
  faThumbtack,
  faBook,
  faDownload,
  faArrowRotateRight,
  faSitemap,
  faScissors,
  faPaste,
} from '@fortawesome/free-solid-svg-icons'
import App from './App.vue'
import { router } from './router'

library.add(
  faPlus,
  faTrash,
  faGear,
  faPaperPlane,
  faStop,
  faComments,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faArrowDown,
  faXmark,
  faWindowMaximize,
  faChevronDown,
  faChevronRight,
  faCheck,
  faClipboardList,
  faWrench,
  faArrowUpRightFromSquare,
  faListUl,
  faListCheck,
  faCircle,
  faCircleCheck,
  faArrowUp,
  faShieldHalved,
  faAnglesUp,
  faAnglesDown,
  faScaleBalanced,
  faUnlock,
  faSliders,
  faMicrochip,
  faCircleQuestion,
  faCircleNotch,
  faCircleExclamation,
  faKey,
  faRightFromBracket,
  faPenToSquare,
  faMagnifyingGlass,
  faFileExport,
  faEllipsis,
  faEllipsisVertical,
  faBars,
  faRobot,
  faTerminal,
  faFolder,
  faFolderOpen,
  faFile,
  faPuzzlePiece,
  faThumbtack,
  faBook,
  faDownload,
  faArrowRotateRight,
  faSitemap,
  faScissors,
  faPaste,
)

const vuetify = createVuetify({
  components,
  directives,
  theme: {
    defaultTheme: 'navoraLight',
    themes: {
      navoraLight: {
        dark: false,
        colors: {
          background: '#f4f6f8',
          surface: '#ffffff',
          primary: '#1b4f72',
          secondary: '#5d6d7e',
          error: '#c0392b',
        },
      },
    },
  },
})

createApp(App).use(router).use(vuetify).component('font-awesome-icon', FontAwesomeIcon).mount('#app')
